name: slsa keyless
on:
  push
env:
  IMAGE: ttl.sh/nais/salsa-keyless-test:1h
jobs:
  keyless:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # ratchet:actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0.8.1
        id: google
        with:
          workload_identity_provider: ${{ secrets.SLSA_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: cosign-kms@plattformsikkerhet-dev-496e.iam.gserviceaccount.com
          token_format: "id_token"
          id_token_audience: ${{ secrets.SLSA_WORKLOAD_IDENTITY_PROVIDER }}
          id_token_include_email: true
          audience: sigstore

      - name: Build and push
        uses: docker/build-push-action@c84f38281176d4c9cdb1626ffafcd6b3911b5d94 # ratchet:docker/build-push-action@v3
        with:
          context: integration-test
          push: true
          tags: ${{ env.IMAGE }}

      - name: Generate provenance, upload and sign image
        uses: ./
        with:
          identity_token: ${{ steps.google.outputs.id_token }}
          docker_pwd: ${{ secrets.GITHUB_TOKEN }}
        env:
          COSIGN_EXPERIMENTAL: "true"