name: NAIS SALSA

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  IMAGE: ttl.sh/nais/salsa-test:1h
  KEY: gcpkms://projects/plattformsikkerhet-dev-496e/locations/europe-north1/keyRings/cosign/cryptoKeys/cosign-test/versions/1

jobs:
  generate-provenance:
    runs-on: ubuntu-20.04
    steps:
      # Required step
      - name: Checkout Code
        uses: actions/checkout@v3

    # For demonstration purpose
    # Credentials needed to authenticate to google kms and
    # sign image. Can be backed in to an action, so users
    # do not have to specify more than a GCP_CREDENTIALS.
      - name: 'Authenticate to Google Cloud'
        id: 'google'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

     # For demonstration purpose
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.IMAGE }}

    # Added to your workflow
      - name: Generate provenance, upload and sign image
      # wil be actions/salsa-action@v01
        uses: ./
        with:
          image: ${{ env.IMAGE }}
          key: ${{ env.KEY }}
          docker_user: ${{ github.actor }}
          docker_pwd: ${{ secrets.GITHUB_TOKEN }}

      # For test output
      - name: Upload provenance
        uses: actions/upload-artifact@v2
        with:
          path: |
            ./salsa.provenance
            ./salsa.raw.txt
            ./salsa.att